/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Query RDAP information for a domain name.
 *
 * @param domainName - Domain name (e.g. "example.com", Unicode IDNs supported)
 * @returns Normalised RDAP domain object
 */
export declare function domain(domainName: string): Promise<any>
/**
 * Query RDAP information for an IP address (IPv4 or IPv6).
 *
 * @param ipAddress - IP address (e.g. "8.8.8.8", "2001:4860:4860::8888")
 * @returns Normalised RDAP IP network object
 */
export declare function ip(ipAddress: string): Promise<any>
/**
 * Query RDAP information for an Autonomous System Number.
 *
 * @param asnValue - ASN number or prefixed form (e.g. "15169", "AS15169")
 * @returns Normalised RDAP autnum object
 */
export declare function asn(asnValue: string): Promise<any>
/**
 * Query RDAP information for a nameserver hostname.
 *
 * @param hostname - Nameserver hostname (e.g. "ns1.google.com")
 * @returns Normalised RDAP nameserver object
 */
export declare function nameserver(hostname: string): Promise<any>
/**
 * Query RDAP information for an entity (contact / registrar).
 *
 * Entities have no global bootstrap registry — an explicit server URL is required.
 *
 * @param handle    - Entity handle (e.g. "ARIN-HN-1")
 * @param serverUrl - RDAP server base URL (e.g. "https://rdap.arin.net/registry")
 * @returns Normalised RDAP entity object
 */
export declare function entity(handle: string, serverUrl: string): Promise<any>
/**
 * Check whether a domain is available for registration.
 *
 * @param name - Domain name (e.g. "example.com")
 * @returns Object with `available` boolean and `expiresAt` string or null
 */
export declare function domainAvailable(name: string): Promise<any>
/**
 * Check availability for multiple domains concurrently.
 *
 * @param names - Array of domain names to check
 * @returns Array of objects with `name`, `available`, `expiresAt`, and `error` fields
 */
export declare function domainAvailableBatch(names: Array<string>): Promise<Array<any>>
/**
 * Stream RDAP ASN results for multiple queries, collecting all events.
 *
 * @param queries - Array of ASN values (e.g. ["15169", "AS32934"])
 * @returns Array of objects with `query`, `result`, and `error` fields
 */
export declare function streamAsn(queries: Array<string>): Promise<Array<any>>
/**
 * Stream RDAP nameserver results for multiple queries, collecting all events.
 *
 * @param queries - Array of nameserver hostnames (e.g. ["ns1.google.com"])
 * @returns Array of objects with `query`, `result`, and `error` fields
 */
export declare function streamNameserver(queries: Array<string>): Promise<Array<any>>
